#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_DohomeApplication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBMASTER")]
	public partial class DBMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBMaster_Barcode(TBMaster_Barcode instance);
    partial void UpdateTBMaster_Barcode(TBMaster_Barcode instance);
    partial void DeleteTBMaster_Barcode(TBMaster_Barcode instance);
    partial void InsertTBMaster_Branch(TBMaster_Branch instance);
    partial void UpdateTBMaster_Branch(TBMaster_Branch instance);
    partial void DeleteTBMaster_Branch(TBMaster_Branch instance);
    partial void InsertTBMaster_Product(TBMaster_Product instance);
    partial void UpdateTBMaster_Product(TBMaster_Product instance);
    partial void DeleteTBMaster_Product(TBMaster_Product instance);
    partial void InsertTBMaster_Site(TBMaster_Site instance);
    partial void UpdateTBMaster_Site(TBMaster_Site instance);
    partial void DeleteTBMaster_Site(TBMaster_Site instance);
    partial void InsertTBMaster_Sloc(TBMaster_Sloc instance);
    partial void UpdateTBMaster_Sloc(TBMaster_Sloc instance);
    partial void DeleteTBMaster_Sloc(TBMaster_Sloc instance);
    partial void InsertTBMaster_Unit(TBMaster_Unit instance);
    partial void UpdateTBMaster_Unit(TBMaster_Unit instance);
    partial void DeleteTBMaster_Unit(TBMaster_Unit instance);
    partial void InsertTBMaster_User(TBMaster_User instance);
    partial void UpdateTBMaster_User(TBMaster_User instance);
    partial void DeleteTBMaster_User(TBMaster_User instance);
    partial void InsertTBMaster_Branch_Site(TBMaster_Branch_Site instance);
    partial void UpdateTBMaster_Branch_Site(TBMaster_Branch_Site instance);
    partial void DeleteTBMaster_Branch_Site(TBMaster_Branch_Site instance);
    partial void InsertTBMaster_Product_Unit(TBMaster_Product_Unit instance);
    partial void UpdateTBMaster_Product_Unit(TBMaster_Product_Unit instance);
    partial void DeleteTBMaster_Product_Unit(TBMaster_Product_Unit instance);
    partial void InsertTBMaster_Pre_Print_Barcode_Reason(TBMaster_Pre_Print_Barcode_Reason instance);
    partial void UpdateTBMaster_Pre_Print_Barcode_Reason(TBMaster_Pre_Print_Barcode_Reason instance);
    partial void DeleteTBMaster_Pre_Print_Barcode_Reason(TBMaster_Pre_Print_Barcode_Reason instance);
    #endregion
		
		public DBMasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBMASTERConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBMaster_Barcode> TBMaster_Barcodes
		{
			get
			{
				return this.GetTable<TBMaster_Barcode>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Branch> TBMaster_Branches
		{
			get
			{
				return this.GetTable<TBMaster_Branch>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Product> TBMaster_Products
		{
			get
			{
				return this.GetTable<TBMaster_Product>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Site> TBMaster_Sites
		{
			get
			{
				return this.GetTable<TBMaster_Site>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Sloc> TBMaster_Slocs
		{
			get
			{
				return this.GetTable<TBMaster_Sloc>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Unit> TBMaster_Units
		{
			get
			{
				return this.GetTable<TBMaster_Unit>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_User> TBMaster_Users
		{
			get
			{
				return this.GetTable<TBMaster_User>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Branch_Site> TBMaster_Branch_Sites
		{
			get
			{
				return this.GetTable<TBMaster_Branch_Site>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Product_Unit> TBMaster_Product_Units
		{
			get
			{
				return this.GetTable<TBMaster_Product_Unit>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Pre_Print_Barcode_Reason> TBMaster_Pre_Print_Barcode_Reasons
		{
			get
			{
				return this.GetTable<TBMaster_Pre_Print_Barcode_Reason>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Barcode")]
	public partial class TBMaster_Barcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PRODUCTCODE;
		
		private string _UNITCODE;
		
		private string _BARCODE;
		
		private short _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRODUCTCODEChanging(string value);
    partial void OnPRODUCTCODEChanged();
    partial void OnUNITCODEChanging(string value);
    partial void OnUNITCODEChanged();
    partial void OnBARCODEChanging(string value);
    partial void OnBARCODEChanged();
    partial void OnSTATUSChanging(short value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Barcode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PRODUCTCODE
		{
			get
			{
				return this._PRODUCTCODE;
			}
			set
			{
				if ((this._PRODUCTCODE != value))
				{
					this.OnPRODUCTCODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTCODE = value;
					this.SendPropertyChanged("PRODUCTCODE");
					this.OnPRODUCTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UNITCODE
		{
			get
			{
				return this._UNITCODE;
			}
			set
			{
				if ((this._UNITCODE != value))
				{
					this.OnUNITCODEChanging(value);
					this.SendPropertyChanging();
					this._UNITCODE = value;
					this.SendPropertyChanged("UNITCODE");
					this.OnUNITCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this.OnBARCODEChanging(value);
					this.SendPropertyChanging();
					this._BARCODE = value;
					this.SendPropertyChanged("BARCODE");
					this.OnBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt NOT NULL")]
		public short STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Branch")]
	public partial class TBMaster_Branch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _OLD_CODE;
		
		private string _MYNAME;
		
		private int _STATUS;
		
		private string _ADDRESS;
		
		private string _TEL;
		
		private string _FAX;
		
		private string _HOTLINE;
		
		private string _TAXID;
		
		private string _BRANCHCODE;
		
		private string _SHORT_NAME;
		
		private string _SERVER_NAME;
		
		private string _SERVER_IP;
		
		private string _DB_MASTER_NAME;
		
		private string _DB_TRANS_NAME;
		
		private string _USER_ID;
		
		private string _PASSWORD;
		
		private string _BRANCHCODE_TAX;
		
		private string _OLD_SERVER_CONNECTION_STRING;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
		private string _BUSINESS_PLACE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnOLD_CODEChanging(string value);
    partial void OnOLD_CODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnSTATUSChanging(int value);
    partial void OnSTATUSChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnTELChanging(string value);
    partial void OnTELChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnHOTLINEChanging(string value);
    partial void OnHOTLINEChanged();
    partial void OnTAXIDChanging(string value);
    partial void OnTAXIDChanged();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnSHORT_NAMEChanging(string value);
    partial void OnSHORT_NAMEChanged();
    partial void OnSERVER_NAMEChanging(string value);
    partial void OnSERVER_NAMEChanged();
    partial void OnSERVER_IPChanging(string value);
    partial void OnSERVER_IPChanged();
    partial void OnDB_MASTER_NAMEChanging(string value);
    partial void OnDB_MASTER_NAMEChanged();
    partial void OnDB_TRANS_NAMEChanging(string value);
    partial void OnDB_TRANS_NAMEChanged();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnBRANCHCODE_TAXChanging(string value);
    partial void OnBRANCHCODE_TAXChanged();
    partial void OnOLD_SERVER_CONNECTION_STRINGChanging(string value);
    partial void OnOLD_SERVER_CONNECTION_STRINGChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    partial void OnBUSINESS_PLACEChanging(string value);
    partial void OnBUSINESS_PLACEChanged();
    #endregion
		
		public TBMaster_Branch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_CODE", DbType="VarChar(50)")]
		public string OLD_CODE
		{
			get
			{
				return this._OLD_CODE;
			}
			set
			{
				if ((this._OLD_CODE != value))
				{
					this.OnOLD_CODEChanging(value);
					this.SendPropertyChanging();
					this._OLD_CODE = value;
					this.SendPropertyChanged("OLD_CODE");
					this.OnOLD_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(150)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int NOT NULL")]
		public int STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(200)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL", DbType="VarChar(50)")]
		public string TEL
		{
			get
			{
				return this._TEL;
			}
			set
			{
				if ((this._TEL != value))
				{
					this.OnTELChanging(value);
					this.SendPropertyChanging();
					this._TEL = value;
					this.SendPropertyChanged("TEL");
					this.OnTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(50)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTLINE", DbType="VarChar(50)")]
		public string HOTLINE
		{
			get
			{
				return this._HOTLINE;
			}
			set
			{
				if ((this._HOTLINE != value))
				{
					this.OnHOTLINEChanging(value);
					this.SendPropertyChanging();
					this._HOTLINE = value;
					this.SendPropertyChanged("HOTLINE");
					this.OnHOTLINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXID", DbType="VarChar(50)")]
		public string TAXID
		{
			get
			{
				return this._TAXID;
			}
			set
			{
				if ((this._TAXID != value))
				{
					this.OnTAXIDChanging(value);
					this.SendPropertyChanging();
					this._TAXID = value;
					this.SendPropertyChanged("TAXID");
					this.OnTAXIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHORT_NAME", DbType="VarChar(50)")]
		public string SHORT_NAME
		{
			get
			{
				return this._SHORT_NAME;
			}
			set
			{
				if ((this._SHORT_NAME != value))
				{
					this.OnSHORT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SHORT_NAME = value;
					this.SendPropertyChanged("SHORT_NAME");
					this.OnSHORT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_NAME", DbType="VarChar(50)")]
		public string SERVER_NAME
		{
			get
			{
				return this._SERVER_NAME;
			}
			set
			{
				if ((this._SERVER_NAME != value))
				{
					this.OnSERVER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SERVER_NAME = value;
					this.SendPropertyChanged("SERVER_NAME");
					this.OnSERVER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_IP", DbType="VarChar(50)")]
		public string SERVER_IP
		{
			get
			{
				return this._SERVER_IP;
			}
			set
			{
				if ((this._SERVER_IP != value))
				{
					this.OnSERVER_IPChanging(value);
					this.SendPropertyChanging();
					this._SERVER_IP = value;
					this.SendPropertyChanged("SERVER_IP");
					this.OnSERVER_IPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_MASTER_NAME", DbType="VarChar(50)")]
		public string DB_MASTER_NAME
		{
			get
			{
				return this._DB_MASTER_NAME;
			}
			set
			{
				if ((this._DB_MASTER_NAME != value))
				{
					this.OnDB_MASTER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DB_MASTER_NAME = value;
					this.SendPropertyChanged("DB_MASTER_NAME");
					this.OnDB_MASTER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_TRANS_NAME", DbType="VarChar(50)")]
		public string DB_TRANS_NAME
		{
			get
			{
				return this._DB_TRANS_NAME;
			}
			set
			{
				if ((this._DB_TRANS_NAME != value))
				{
					this.OnDB_TRANS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DB_TRANS_NAME = value;
					this.SendPropertyChanged("DB_TRANS_NAME");
					this.OnDB_TRANS_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="VarChar(50)")]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE_TAX", DbType="VarChar(50)")]
		public string BRANCHCODE_TAX
		{
			get
			{
				return this._BRANCHCODE_TAX;
			}
			set
			{
				if ((this._BRANCHCODE_TAX != value))
				{
					this.OnBRANCHCODE_TAXChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE_TAX = value;
					this.SendPropertyChanged("BRANCHCODE_TAX");
					this.OnBRANCHCODE_TAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_SERVER_CONNECTION_STRING", DbType="VarChar(250)")]
		public string OLD_SERVER_CONNECTION_STRING
		{
			get
			{
				return this._OLD_SERVER_CONNECTION_STRING;
			}
			set
			{
				if ((this._OLD_SERVER_CONNECTION_STRING != value))
				{
					this.OnOLD_SERVER_CONNECTION_STRINGChanging(value);
					this.SendPropertyChanging();
					this._OLD_SERVER_CONNECTION_STRING = value;
					this.SendPropertyChanged("OLD_SERVER_CONNECTION_STRING");
					this.OnOLD_SERVER_CONNECTION_STRINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSINESS_PLACE", DbType="VarChar(20)")]
		public string BUSINESS_PLACE
		{
			get
			{
				return this._BUSINESS_PLACE;
			}
			set
			{
				if ((this._BUSINESS_PLACE != value))
				{
					this.OnBUSINESS_PLACEChanging(value);
					this.SendPropertyChanging();
					this._BUSINESS_PLACE = value;
					this.SendPropertyChanged("BUSINESS_PLACE");
					this.OnBUSINESS_PLACEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Product")]
	public partial class TBMaster_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _NAMETH;
		
		private string _NAMEEN;
		
		private string _NAMESEARCH;
		
		private short _TAXTYPE;
		
		private short _STATUS;
		
		private string _STOCKUNIT;
		
		private string _MCCODE;
		
		private string _PRODUCTBRAND;
		
		private string _MATERIALTYPE;
		
		private string _MAINCODE;
		
		private short _CNFLAG;
		
		private short _SHOWPRICEFLAG;
		
		private short _CRCHARGEFLAG;
		
		private string _OLDCODE;
		
		private string _MTPOS;
		
		private int _IS_BATCH;
		
		private int _IS_SERIAL;
		
		private int _IS_EXPIRE_DATE;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnNAMETHChanging(string value);
    partial void OnNAMETHChanged();
    partial void OnNAMEENChanging(string value);
    partial void OnNAMEENChanged();
    partial void OnNAMESEARCHChanging(string value);
    partial void OnNAMESEARCHChanged();
    partial void OnTAXTYPEChanging(short value);
    partial void OnTAXTYPEChanged();
    partial void OnSTATUSChanging(short value);
    partial void OnSTATUSChanged();
    partial void OnSTOCKUNITChanging(string value);
    partial void OnSTOCKUNITChanged();
    partial void OnMCCODEChanging(string value);
    partial void OnMCCODEChanged();
    partial void OnPRODUCTBRANDChanging(string value);
    partial void OnPRODUCTBRANDChanged();
    partial void OnMATERIALTYPEChanging(string value);
    partial void OnMATERIALTYPEChanged();
    partial void OnMAINCODEChanging(string value);
    partial void OnMAINCODEChanged();
    partial void OnCNFLAGChanging(short value);
    partial void OnCNFLAGChanged();
    partial void OnSHOWPRICEFLAGChanging(short value);
    partial void OnSHOWPRICEFLAGChanged();
    partial void OnCRCHARGEFLAGChanging(short value);
    partial void OnCRCHARGEFLAGChanged();
    partial void OnOLDCODEChanging(string value);
    partial void OnOLDCODEChanged();
    partial void OnMTPOSChanging(string value);
    partial void OnMTPOSChanged();
    partial void OnIS_BATCHChanging(int value);
    partial void OnIS_BATCHChanged();
    partial void OnIS_SERIALChanging(int value);
    partial void OnIS_SERIALChanged();
    partial void OnIS_EXPIRE_DATEChanging(int value);
    partial void OnIS_EXPIRE_DATEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMETH", DbType="VarChar(250)")]
		public string NAMETH
		{
			get
			{
				return this._NAMETH;
			}
			set
			{
				if ((this._NAMETH != value))
				{
					this.OnNAMETHChanging(value);
					this.SendPropertyChanging();
					this._NAMETH = value;
					this.SendPropertyChanged("NAMETH");
					this.OnNAMETHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMEEN", DbType="VarChar(250)")]
		public string NAMEEN
		{
			get
			{
				return this._NAMEEN;
			}
			set
			{
				if ((this._NAMEEN != value))
				{
					this.OnNAMEENChanging(value);
					this.SendPropertyChanging();
					this._NAMEEN = value;
					this.SendPropertyChanged("NAMEEN");
					this.OnNAMEENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMESEARCH", DbType="VarChar(250)")]
		public string NAMESEARCH
		{
			get
			{
				return this._NAMESEARCH;
			}
			set
			{
				if ((this._NAMESEARCH != value))
				{
					this.OnNAMESEARCHChanging(value);
					this.SendPropertyChanging();
					this._NAMESEARCH = value;
					this.SendPropertyChanged("NAMESEARCH");
					this.OnNAMESEARCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXTYPE", DbType="SmallInt NOT NULL")]
		public short TAXTYPE
		{
			get
			{
				return this._TAXTYPE;
			}
			set
			{
				if ((this._TAXTYPE != value))
				{
					this.OnTAXTYPEChanging(value);
					this.SendPropertyChanging();
					this._TAXTYPE = value;
					this.SendPropertyChanged("TAXTYPE");
					this.OnTAXTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt NOT NULL")]
		public short STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKUNIT", DbType="VarChar(20)")]
		public string STOCKUNIT
		{
			get
			{
				return this._STOCKUNIT;
			}
			set
			{
				if ((this._STOCKUNIT != value))
				{
					this.OnSTOCKUNITChanging(value);
					this.SendPropertyChanging();
					this._STOCKUNIT = value;
					this.SendPropertyChanged("STOCKUNIT");
					this.OnSTOCKUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MCCODE", DbType="VarChar(20)")]
		public string MCCODE
		{
			get
			{
				return this._MCCODE;
			}
			set
			{
				if ((this._MCCODE != value))
				{
					this.OnMCCODEChanging(value);
					this.SendPropertyChanging();
					this._MCCODE = value;
					this.SendPropertyChanged("MCCODE");
					this.OnMCCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTBRAND", DbType="VarChar(20)")]
		public string PRODUCTBRAND
		{
			get
			{
				return this._PRODUCTBRAND;
			}
			set
			{
				if ((this._PRODUCTBRAND != value))
				{
					this.OnPRODUCTBRANDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTBRAND = value;
					this.SendPropertyChanged("PRODUCTBRAND");
					this.OnPRODUCTBRANDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIALTYPE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MATERIALTYPE
		{
			get
			{
				return this._MATERIALTYPE;
			}
			set
			{
				if ((this._MATERIALTYPE != value))
				{
					this.OnMATERIALTYPEChanging(value);
					this.SendPropertyChanging();
					this._MATERIALTYPE = value;
					this.SendPropertyChanged("MATERIALTYPE");
					this.OnMATERIALTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAINCODE", DbType="VarChar(20)")]
		public string MAINCODE
		{
			get
			{
				return this._MAINCODE;
			}
			set
			{
				if ((this._MAINCODE != value))
				{
					this.OnMAINCODEChanging(value);
					this.SendPropertyChanging();
					this._MAINCODE = value;
					this.SendPropertyChanged("MAINCODE");
					this.OnMAINCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNFLAG", DbType="SmallInt NOT NULL")]
		public short CNFLAG
		{
			get
			{
				return this._CNFLAG;
			}
			set
			{
				if ((this._CNFLAG != value))
				{
					this.OnCNFLAGChanging(value);
					this.SendPropertyChanging();
					this._CNFLAG = value;
					this.SendPropertyChanged("CNFLAG");
					this.OnCNFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOWPRICEFLAG", DbType="SmallInt NOT NULL")]
		public short SHOWPRICEFLAG
		{
			get
			{
				return this._SHOWPRICEFLAG;
			}
			set
			{
				if ((this._SHOWPRICEFLAG != value))
				{
					this.OnSHOWPRICEFLAGChanging(value);
					this.SendPropertyChanging();
					this._SHOWPRICEFLAG = value;
					this.SendPropertyChanged("SHOWPRICEFLAG");
					this.OnSHOWPRICEFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRCHARGEFLAG", DbType="SmallInt NOT NULL")]
		public short CRCHARGEFLAG
		{
			get
			{
				return this._CRCHARGEFLAG;
			}
			set
			{
				if ((this._CRCHARGEFLAG != value))
				{
					this.OnCRCHARGEFLAGChanging(value);
					this.SendPropertyChanging();
					this._CRCHARGEFLAG = value;
					this.SendPropertyChanged("CRCHARGEFLAG");
					this.OnCRCHARGEFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLDCODE", DbType="VarChar(20)")]
		public string OLDCODE
		{
			get
			{
				return this._OLDCODE;
			}
			set
			{
				if ((this._OLDCODE != value))
				{
					this.OnOLDCODEChanging(value);
					this.SendPropertyChanging();
					this._OLDCODE = value;
					this.SendPropertyChanged("OLDCODE");
					this.OnOLDCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTPOS", DbType="VarChar(20)")]
		public string MTPOS
		{
			get
			{
				return this._MTPOS;
			}
			set
			{
				if ((this._MTPOS != value))
				{
					this.OnMTPOSChanging(value);
					this.SendPropertyChanging();
					this._MTPOS = value;
					this.SendPropertyChanged("MTPOS");
					this.OnMTPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_BATCH", DbType="Int NOT NULL")]
		public int IS_BATCH
		{
			get
			{
				return this._IS_BATCH;
			}
			set
			{
				if ((this._IS_BATCH != value))
				{
					this.OnIS_BATCHChanging(value);
					this.SendPropertyChanging();
					this._IS_BATCH = value;
					this.SendPropertyChanged("IS_BATCH");
					this.OnIS_BATCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_SERIAL", DbType="Int NOT NULL")]
		public int IS_SERIAL
		{
			get
			{
				return this._IS_SERIAL;
			}
			set
			{
				if ((this._IS_SERIAL != value))
				{
					this.OnIS_SERIALChanging(value);
					this.SendPropertyChanging();
					this._IS_SERIAL = value;
					this.SendPropertyChanged("IS_SERIAL");
					this.OnIS_SERIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_EXPIRE_DATE", DbType="Int NOT NULL")]
		public int IS_EXPIRE_DATE
		{
			get
			{
				return this._IS_EXPIRE_DATE;
			}
			set
			{
				if ((this._IS_EXPIRE_DATE != value))
				{
					this.OnIS_EXPIRE_DATEChanging(value);
					this.SendPropertyChanging();
					this._IS_EXPIRE_DATE = value;
					this.SendPropertyChanged("IS_EXPIRE_DATE");
					this.OnIS_EXPIRE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Site")]
	public partial class TBMaster_Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private System.Nullable<int> _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Site()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(100)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Sloc")]
	public partial class TBMaster_Sloc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SITECODE;
		
		private string _SLOC;
		
		private string _SLOC_NAME;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSLOCChanging(string value);
    partial void OnSLOCChanged();
    partial void OnSLOC_NAMEChanging(string value);
    partial void OnSLOC_NAMEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Sloc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SLOC
		{
			get
			{
				return this._SLOC;
			}
			set
			{
				if ((this._SLOC != value))
				{
					this.OnSLOCChanging(value);
					this.SendPropertyChanging();
					this._SLOC = value;
					this.SendPropertyChanged("SLOC");
					this.OnSLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC_NAME", DbType="VarChar(150)")]
		public string SLOC_NAME
		{
			get
			{
				return this._SLOC_NAME;
			}
			set
			{
				if ((this._SLOC_NAME != value))
				{
					this.OnSLOC_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SLOC_NAME = value;
					this.SendPropertyChanged("SLOC_NAME");
					this.OnSLOC_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Unit")]
	public partial class TBMaster_Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private short _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnSTATUSChanging(short value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(50)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt NOT NULL")]
		public short STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_User")]
	public partial class TBMaster_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _JOBKEY;
		
		private string _POSITION;
		
		private System.Nullable<System.DateTime> _BEGINDATE;
		
		private System.Nullable<System.DateTime> _ENDDATE;
		
		private string _WERKS;
		
		private System.Nullable<int> _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnJOBKEYChanging(string value);
    partial void OnJOBKEYChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnBEGINDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBEGINDATEChanged();
    partial void OnENDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnENDDATEChanged();
    partial void OnWERKSChanging(string value);
    partial void OnWERKSChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(250)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(50)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="VarChar(50)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBKEY", DbType="VarChar(50)")]
		public string JOBKEY
		{
			get
			{
				return this._JOBKEY;
			}
			set
			{
				if ((this._JOBKEY != value))
				{
					this.OnJOBKEYChanging(value);
					this.SendPropertyChanging();
					this._JOBKEY = value;
					this.SendPropertyChanged("JOBKEY");
					this.OnJOBKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGINDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BEGINDATE
		{
			get
			{
				return this._BEGINDATE;
			}
			set
			{
				if ((this._BEGINDATE != value))
				{
					this.OnBEGINDATEChanging(value);
					this.SendPropertyChanging();
					this._BEGINDATE = value;
					this.SendPropertyChanged("BEGINDATE");
					this.OnBEGINDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this.OnENDDATEChanging(value);
					this.SendPropertyChanging();
					this._ENDDATE = value;
					this.SendPropertyChanged("ENDDATE");
					this.OnENDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WERKS", DbType="VarChar(50)")]
		public string WERKS
		{
			get
			{
				return this._WERKS;
			}
			set
			{
				if ((this._WERKS != value))
				{
					this.OnWERKSChanging(value);
					this.SendPropertyChanging();
					this._WERKS = value;
					this.SendPropertyChanged("WERKS");
					this.OnWERKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Branch_Site")]
	public partial class TBMaster_Branch_Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BRANCHCODE;
		
		private string _SITECODE;
		
		private string _SITENAME;
		
		private System.Nullable<int> _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
		private int _IS_STORE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSITENAMEChanging(string value);
    partial void OnSITENAMEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    partial void OnIS_STOREChanging(int value);
    partial void OnIS_STOREChanged();
    #endregion
		
		public TBMaster_Branch_Site()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITENAME", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string SITENAME
		{
			get
			{
				return this._SITENAME;
			}
			set
			{
				if ((this._SITENAME != value))
				{
					this.OnSITENAMEChanging(value);
					this.SendPropertyChanging();
					this._SITENAME = value;
					this.SendPropertyChanged("SITENAME");
					this.OnSITENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_STORE", DbType="Int NOT NULL")]
		public int IS_STORE
		{
			get
			{
				return this._IS_STORE;
			}
			set
			{
				if ((this._IS_STORE != value))
				{
					this.OnIS_STOREChanging(value);
					this.SendPropertyChanging();
					this._IS_STORE = value;
					this.SendPropertyChanged("IS_STORE");
					this.OnIS_STOREChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Product_Unit")]
	public partial class TBMaster_Product_Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PRODUCTCODE;
		
		private string _UNITCODE;
		
		private System.Nullable<decimal> _UNITRATE;
		
		private decimal _UNITWEIGHT;
		
		private short _STATUS;
		
		private System.Nullable<bool> _UNIT_BUN_CODE;
		
		private System.Nullable<bool> _UNIT_OUN_CODE;
		
		private System.Nullable<bool> _UNIT_DI_CODE;
		
		private System.Nullable<bool> _UNIT_SUN_CODE;
		
		private System.Nullable<decimal> _N_WEIGHT;
		
		private System.Nullable<decimal> _G_WEIGHT;
		
		private string _WEIGHT_UNIT;
		
		private System.Nullable<decimal> _THICK;
		
		private System.Nullable<decimal> _WIDTH;
		
		private System.Nullable<decimal> _HIGH;
		
		private string _UNIT_OF_SIZE;
		
		private System.Nullable<decimal> _VOLUME;
		
		private string _UNIT_OF_VOLUME;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRODUCTCODEChanging(string value);
    partial void OnPRODUCTCODEChanged();
    partial void OnUNITCODEChanging(string value);
    partial void OnUNITCODEChanged();
    partial void OnUNITRATEChanging(System.Nullable<decimal> value);
    partial void OnUNITRATEChanged();
    partial void OnUNITWEIGHTChanging(decimal value);
    partial void OnUNITWEIGHTChanged();
    partial void OnSTATUSChanging(short value);
    partial void OnSTATUSChanged();
    partial void OnUNIT_BUN_CODEChanging(System.Nullable<bool> value);
    partial void OnUNIT_BUN_CODEChanged();
    partial void OnUNIT_OUN_CODEChanging(System.Nullable<bool> value);
    partial void OnUNIT_OUN_CODEChanged();
    partial void OnUNIT_DI_CODEChanging(System.Nullable<bool> value);
    partial void OnUNIT_DI_CODEChanged();
    partial void OnUNIT_SUN_CODEChanging(System.Nullable<bool> value);
    partial void OnUNIT_SUN_CODEChanged();
    partial void OnN_WEIGHTChanging(System.Nullable<decimal> value);
    partial void OnN_WEIGHTChanged();
    partial void OnG_WEIGHTChanging(System.Nullable<decimal> value);
    partial void OnG_WEIGHTChanged();
    partial void OnWEIGHT_UNITChanging(string value);
    partial void OnWEIGHT_UNITChanged();
    partial void OnTHICKChanging(System.Nullable<decimal> value);
    partial void OnTHICKChanged();
    partial void OnWIDTHChanging(System.Nullable<decimal> value);
    partial void OnWIDTHChanged();
    partial void OnHIGHChanging(System.Nullable<decimal> value);
    partial void OnHIGHChanged();
    partial void OnUNIT_OF_SIZEChanging(string value);
    partial void OnUNIT_OF_SIZEChanged();
    partial void OnVOLUMEChanging(System.Nullable<decimal> value);
    partial void OnVOLUMEChanged();
    partial void OnUNIT_OF_VOLUMEChanging(string value);
    partial void OnUNIT_OF_VOLUMEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Product_Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTCODE", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PRODUCTCODE
		{
			get
			{
				return this._PRODUCTCODE;
			}
			set
			{
				if ((this._PRODUCTCODE != value))
				{
					this.OnPRODUCTCODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTCODE = value;
					this.SendPropertyChanged("PRODUCTCODE");
					this.OnPRODUCTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITCODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UNITCODE
		{
			get
			{
				return this._UNITCODE;
			}
			set
			{
				if ((this._UNITCODE != value))
				{
					this.OnUNITCODEChanging(value);
					this.SendPropertyChanging();
					this._UNITCODE = value;
					this.SendPropertyChanged("UNITCODE");
					this.OnUNITCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITRATE", DbType="Money")]
		public System.Nullable<decimal> UNITRATE
		{
			get
			{
				return this._UNITRATE;
			}
			set
			{
				if ((this._UNITRATE != value))
				{
					this.OnUNITRATEChanging(value);
					this.SendPropertyChanging();
					this._UNITRATE = value;
					this.SendPropertyChanged("UNITRATE");
					this.OnUNITRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITWEIGHT", DbType="Money NOT NULL")]
		public decimal UNITWEIGHT
		{
			get
			{
				return this._UNITWEIGHT;
			}
			set
			{
				if ((this._UNITWEIGHT != value))
				{
					this.OnUNITWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._UNITWEIGHT = value;
					this.SendPropertyChanged("UNITWEIGHT");
					this.OnUNITWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt NOT NULL")]
		public short STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_BUN_CODE", DbType="Bit")]
		public System.Nullable<bool> UNIT_BUN_CODE
		{
			get
			{
				return this._UNIT_BUN_CODE;
			}
			set
			{
				if ((this._UNIT_BUN_CODE != value))
				{
					this.OnUNIT_BUN_CODEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_BUN_CODE = value;
					this.SendPropertyChanged("UNIT_BUN_CODE");
					this.OnUNIT_BUN_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_OUN_CODE", DbType="Bit")]
		public System.Nullable<bool> UNIT_OUN_CODE
		{
			get
			{
				return this._UNIT_OUN_CODE;
			}
			set
			{
				if ((this._UNIT_OUN_CODE != value))
				{
					this.OnUNIT_OUN_CODEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_OUN_CODE = value;
					this.SendPropertyChanged("UNIT_OUN_CODE");
					this.OnUNIT_OUN_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_DI_CODE", DbType="Bit")]
		public System.Nullable<bool> UNIT_DI_CODE
		{
			get
			{
				return this._UNIT_DI_CODE;
			}
			set
			{
				if ((this._UNIT_DI_CODE != value))
				{
					this.OnUNIT_DI_CODEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_DI_CODE = value;
					this.SendPropertyChanged("UNIT_DI_CODE");
					this.OnUNIT_DI_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_SUN_CODE", DbType="Bit")]
		public System.Nullable<bool> UNIT_SUN_CODE
		{
			get
			{
				return this._UNIT_SUN_CODE;
			}
			set
			{
				if ((this._UNIT_SUN_CODE != value))
				{
					this.OnUNIT_SUN_CODEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_SUN_CODE = value;
					this.SendPropertyChanged("UNIT_SUN_CODE");
					this.OnUNIT_SUN_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_WEIGHT", DbType="Money")]
		public System.Nullable<decimal> N_WEIGHT
		{
			get
			{
				return this._N_WEIGHT;
			}
			set
			{
				if ((this._N_WEIGHT != value))
				{
					this.OnN_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._N_WEIGHT = value;
					this.SendPropertyChanged("N_WEIGHT");
					this.OnN_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_WEIGHT", DbType="Money")]
		public System.Nullable<decimal> G_WEIGHT
		{
			get
			{
				return this._G_WEIGHT;
			}
			set
			{
				if ((this._G_WEIGHT != value))
				{
					this.OnG_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._G_WEIGHT = value;
					this.SendPropertyChanged("G_WEIGHT");
					this.OnG_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT_UNIT", DbType="VarChar(50)")]
		public string WEIGHT_UNIT
		{
			get
			{
				return this._WEIGHT_UNIT;
			}
			set
			{
				if ((this._WEIGHT_UNIT != value))
				{
					this.OnWEIGHT_UNITChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT_UNIT = value;
					this.SendPropertyChanged("WEIGHT_UNIT");
					this.OnWEIGHT_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THICK", DbType="Money")]
		public System.Nullable<decimal> THICK
		{
			get
			{
				return this._THICK;
			}
			set
			{
				if ((this._THICK != value))
				{
					this.OnTHICKChanging(value);
					this.SendPropertyChanging();
					this._THICK = value;
					this.SendPropertyChanged("THICK");
					this.OnTHICKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIDTH", DbType="Money")]
		public System.Nullable<decimal> WIDTH
		{
			get
			{
				return this._WIDTH;
			}
			set
			{
				if ((this._WIDTH != value))
				{
					this.OnWIDTHChanging(value);
					this.SendPropertyChanging();
					this._WIDTH = value;
					this.SendPropertyChanged("WIDTH");
					this.OnWIDTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIGH", DbType="Money")]
		public System.Nullable<decimal> HIGH
		{
			get
			{
				return this._HIGH;
			}
			set
			{
				if ((this._HIGH != value))
				{
					this.OnHIGHChanging(value);
					this.SendPropertyChanging();
					this._HIGH = value;
					this.SendPropertyChanged("HIGH");
					this.OnHIGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_OF_SIZE", DbType="VarChar(50)")]
		public string UNIT_OF_SIZE
		{
			get
			{
				return this._UNIT_OF_SIZE;
			}
			set
			{
				if ((this._UNIT_OF_SIZE != value))
				{
					this.OnUNIT_OF_SIZEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_OF_SIZE = value;
					this.SendPropertyChanged("UNIT_OF_SIZE");
					this.OnUNIT_OF_SIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOLUME", DbType="Money")]
		public System.Nullable<decimal> VOLUME
		{
			get
			{
				return this._VOLUME;
			}
			set
			{
				if ((this._VOLUME != value))
				{
					this.OnVOLUMEChanging(value);
					this.SendPropertyChanging();
					this._VOLUME = value;
					this.SendPropertyChanged("VOLUME");
					this.OnVOLUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_OF_VOLUME", DbType="VarChar(50)")]
		public string UNIT_OF_VOLUME
		{
			get
			{
				return this._UNIT_OF_VOLUME;
			}
			set
			{
				if ((this._UNIT_OF_VOLUME != value))
				{
					this.OnUNIT_OF_VOLUMEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_OF_VOLUME = value;
					this.SendPropertyChanged("UNIT_OF_VOLUME");
					this.OnUNIT_OF_VOLUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Pre_Print_Barcode_Reason")]
	public partial class TBMaster_Pre_Print_Barcode_Reason : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _REASON_TEXT;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnREASON_TEXTChanging(string value);
    partial void OnREASON_TEXTChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Pre_Print_Barcode_Reason()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REASON_TEXT", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string REASON_TEXT
		{
			get
			{
				return this._REASON_TEXT;
			}
			set
			{
				if ((this._REASON_TEXT != value))
				{
					this.OnREASON_TEXTChanging(value);
					this.SendPropertyChanging();
					this._REASON_TEXT = value;
					this.SendPropertyChanged("REASON_TEXT");
					this.OnREASON_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
