#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_DohomeApplication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBTRANS")]
	public partial class DBTransDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBTrans_PRE_Print_Barcode(TBTrans_PRE_Print_Barcode instance);
    partial void UpdateTBTrans_PRE_Print_Barcode(TBTrans_PRE_Print_Barcode instance);
    partial void DeleteTBTrans_PRE_Print_Barcode(TBTrans_PRE_Print_Barcode instance);
    partial void InsertTBTrans_PRE_Print_BarcodeSub(TBTrans_PRE_Print_BarcodeSub instance);
    partial void UpdateTBTrans_PRE_Print_BarcodeSub(TBTrans_PRE_Print_BarcodeSub instance);
    partial void DeleteTBTrans_PRE_Print_BarcodeSub(TBTrans_PRE_Print_BarcodeSub instance);
    partial void InsertTBTrans_PRE_Print_MessageSub(TBTrans_PRE_Print_MessageSub instance);
    partial void UpdateTBTrans_PRE_Print_MessageSub(TBTrans_PRE_Print_MessageSub instance);
    partial void DeleteTBTrans_PRE_Print_MessageSub(TBTrans_PRE_Print_MessageSub instance);
    partial void InsertTBTrans_PRE_Print_Message(TBTrans_PRE_Print_Message instance);
    partial void UpdateTBTrans_PRE_Print_Message(TBTrans_PRE_Print_Message instance);
    partial void DeleteTBTrans_PRE_Print_Message(TBTrans_PRE_Print_Message instance);
    #endregion
		
		public DBTransDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBTRANSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTransDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTransDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTransDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTransDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBTrans_PRE_Print_Barcode> TBTrans_PRE_Print_Barcodes
		{
			get
			{
				return this.GetTable<TBTrans_PRE_Print_Barcode>();
			}
		}
		
		public System.Data.Linq.Table<TBTrans_PRE_Print_BarcodeSub> TBTrans_PRE_Print_BarcodeSubs
		{
			get
			{
				return this.GetTable<TBTrans_PRE_Print_BarcodeSub>();
			}
		}
		
		public System.Data.Linq.Table<TBTrans_PRE_Print_MessageSub> TBTrans_PRE_Print_MessageSubs
		{
			get
			{
				return this.GetTable<TBTrans_PRE_Print_MessageSub>();
			}
		}
		
		public System.Data.Linq.Table<TBTrans_PRE_Print_Message> TBTrans_PRE_Print_Messages
		{
			get
			{
				return this.GetTable<TBTrans_PRE_Print_Message>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_PRE_Print_Barcode")]
	public partial class TBTrans_PRE_Print_Barcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _BRANCHCODE;
		
		private string _SITECODE;
		
		private string _SLOC;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEUSER;
		
		private string _STATUS;
		
		private int _PRINT_NUMBER;
		
		private System.Nullable<System.DateTime> _PRINTDATE;
		
		private string _PRINTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSLOCChanging(string value);
    partial void OnSLOCChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATEUSERChanging(string value);
    partial void OnCREATEUSERChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnPRINT_NUMBERChanging(int value);
    partial void OnPRINT_NUMBERChanged();
    partial void OnPRINTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPRINTDATEChanged();
    partial void OnPRINTUSERChanging(string value);
    partial void OnPRINTUSERChanged();
    #endregion
		
		public TBTrans_PRE_Print_Barcode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(50)")]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC", DbType="VarChar(50)")]
		public string SLOC
		{
			get
			{
				return this._SLOC;
			}
			set
			{
				if ((this._SLOC != value))
				{
					this.OnSLOCChanging(value);
					this.SendPropertyChanging();
					this._SLOC = value;
					this.SendPropertyChanged("SLOC");
					this.OnSLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEUSER", DbType="VarChar(50)")]
		public string CREATEUSER
		{
			get
			{
				return this._CREATEUSER;
			}
			set
			{
				if ((this._CREATEUSER != value))
				{
					this.OnCREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._CREATEUSER = value;
					this.SendPropertyChanged("CREATEUSER");
					this.OnCREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINT_NUMBER", DbType="Int NOT NULL")]
		public int PRINT_NUMBER
		{
			get
			{
				return this._PRINT_NUMBER;
			}
			set
			{
				if ((this._PRINT_NUMBER != value))
				{
					this.OnPRINT_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PRINT_NUMBER = value;
					this.SendPropertyChanged("PRINT_NUMBER");
					this.OnPRINT_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PRINTDATE
		{
			get
			{
				return this._PRINTDATE;
			}
			set
			{
				if ((this._PRINTDATE != value))
				{
					this.OnPRINTDATEChanging(value);
					this.SendPropertyChanging();
					this._PRINTDATE = value;
					this.SendPropertyChanged("PRINTDATE");
					this.OnPRINTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTUSER", DbType="VarChar(50)")]
		public string PRINTUSER
		{
			get
			{
				return this._PRINTUSER;
			}
			set
			{
				if ((this._PRINTUSER != value))
				{
					this.OnPRINTUSERChanging(value);
					this.SendPropertyChanging();
					this._PRINTUSER = value;
					this.SendPropertyChanged("PRINTUSER");
					this.OnPRINTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_PRE_Print_BarcodeSub")]
	public partial class TBTrans_PRE_Print_BarcodeSub : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private int _ROWORDER;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _BRANCHCODE;
		
		private string _SITECODE;
		
		private string _SLOC;
		
		private string _PRODUCTCODE;
		
		private string _PRODUCTNAME;
		
		private string _BARCODE_REQ;
		
		private System.Nullable<decimal> _QUANTITY_REQ;
		
		private string _UNIT_REQ;
		
		private System.Nullable<decimal> _UNIT_RATE_REQ;
		
		private System.Nullable<decimal> _QUANTITY_TRAN;
		
		private string _UNIT_TRAN;
		
		private System.Nullable<System.DateTime> _PRINTDATE;
		
		private string _CAUSE_REQUEST;
		
		private string _GR_DOCNO;
		
		private string _GR_YEAR;
		
		private string _PRINTUSER;
		
		private string _STATUS;
		
		private System.Nullable<System.DateTime> _APPROVEDATE;
		
		private string _APPROVEUSER;
		
		private string _APPROVE_REMARK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnROWORDERChanging(int value);
    partial void OnROWORDERChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSLOCChanging(string value);
    partial void OnSLOCChanged();
    partial void OnPRODUCTCODEChanging(string value);
    partial void OnPRODUCTCODEChanged();
    partial void OnPRODUCTNAMEChanging(string value);
    partial void OnPRODUCTNAMEChanged();
    partial void OnBARCODE_REQChanging(string value);
    partial void OnBARCODE_REQChanged();
    partial void OnQUANTITY_REQChanging(System.Nullable<decimal> value);
    partial void OnQUANTITY_REQChanged();
    partial void OnUNIT_REQChanging(string value);
    partial void OnUNIT_REQChanged();
    partial void OnUNIT_RATE_REQChanging(System.Nullable<decimal> value);
    partial void OnUNIT_RATE_REQChanged();
    partial void OnQUANTITY_TRANChanging(System.Nullable<decimal> value);
    partial void OnQUANTITY_TRANChanged();
    partial void OnUNIT_TRANChanging(string value);
    partial void OnUNIT_TRANChanged();
    partial void OnPRINTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPRINTDATEChanged();
    partial void OnCAUSE_REQUESTChanging(string value);
    partial void OnCAUSE_REQUESTChanged();
    partial void OnGR_DOCNOChanging(string value);
    partial void OnGR_DOCNOChanged();
    partial void OnGR_YEARChanging(string value);
    partial void OnGR_YEARChanged();
    partial void OnPRINTUSERChanging(string value);
    partial void OnPRINTUSERChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnAPPROVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnAPPROVEDATEChanged();
    partial void OnAPPROVEUSERChanging(string value);
    partial void OnAPPROVEUSERChanged();
    partial void OnAPPROVE_REMARKChanging(string value);
    partial void OnAPPROVE_REMARKChanged();
    #endregion
		
		public TBTrans_PRE_Print_BarcodeSub()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWORDER", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ROWORDER
		{
			get
			{
				return this._ROWORDER;
			}
			set
			{
				if ((this._ROWORDER != value))
				{
					this.OnROWORDERChanging(value);
					this.SendPropertyChanging();
					this._ROWORDER = value;
					this.SendPropertyChanged("ROWORDER");
					this.OnROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(50)")]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC", DbType="VarChar(50)")]
		public string SLOC
		{
			get
			{
				return this._SLOC;
			}
			set
			{
				if ((this._SLOC != value))
				{
					this.OnSLOCChanging(value);
					this.SendPropertyChanging();
					this._SLOC = value;
					this.SendPropertyChanged("SLOC");
					this.OnSLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTCODE", DbType="VarChar(50)")]
		public string PRODUCTCODE
		{
			get
			{
				return this._PRODUCTCODE;
			}
			set
			{
				if ((this._PRODUCTCODE != value))
				{
					this.OnPRODUCTCODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTCODE = value;
					this.SendPropertyChanged("PRODUCTCODE");
					this.OnPRODUCTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTNAME", DbType="VarChar(150)")]
		public string PRODUCTNAME
		{
			get
			{
				return this._PRODUCTNAME;
			}
			set
			{
				if ((this._PRODUCTNAME != value))
				{
					this.OnPRODUCTNAMEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTNAME = value;
					this.SendPropertyChanged("PRODUCTNAME");
					this.OnPRODUCTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE_REQ", DbType="VarChar(50)")]
		public string BARCODE_REQ
		{
			get
			{
				return this._BARCODE_REQ;
			}
			set
			{
				if ((this._BARCODE_REQ != value))
				{
					this.OnBARCODE_REQChanging(value);
					this.SendPropertyChanging();
					this._BARCODE_REQ = value;
					this.SendPropertyChanged("BARCODE_REQ");
					this.OnBARCODE_REQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY_REQ", DbType="Money")]
		public System.Nullable<decimal> QUANTITY_REQ
		{
			get
			{
				return this._QUANTITY_REQ;
			}
			set
			{
				if ((this._QUANTITY_REQ != value))
				{
					this.OnQUANTITY_REQChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY_REQ = value;
					this.SendPropertyChanged("QUANTITY_REQ");
					this.OnQUANTITY_REQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_REQ", DbType="VarChar(50)")]
		public string UNIT_REQ
		{
			get
			{
				return this._UNIT_REQ;
			}
			set
			{
				if ((this._UNIT_REQ != value))
				{
					this.OnUNIT_REQChanging(value);
					this.SendPropertyChanging();
					this._UNIT_REQ = value;
					this.SendPropertyChanged("UNIT_REQ");
					this.OnUNIT_REQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_RATE_REQ", DbType="Money")]
		public System.Nullable<decimal> UNIT_RATE_REQ
		{
			get
			{
				return this._UNIT_RATE_REQ;
			}
			set
			{
				if ((this._UNIT_RATE_REQ != value))
				{
					this.OnUNIT_RATE_REQChanging(value);
					this.SendPropertyChanging();
					this._UNIT_RATE_REQ = value;
					this.SendPropertyChanged("UNIT_RATE_REQ");
					this.OnUNIT_RATE_REQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY_TRAN", DbType="Money")]
		public System.Nullable<decimal> QUANTITY_TRAN
		{
			get
			{
				return this._QUANTITY_TRAN;
			}
			set
			{
				if ((this._QUANTITY_TRAN != value))
				{
					this.OnQUANTITY_TRANChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY_TRAN = value;
					this.SendPropertyChanged("QUANTITY_TRAN");
					this.OnQUANTITY_TRANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_TRAN", DbType="VarChar(50)")]
		public string UNIT_TRAN
		{
			get
			{
				return this._UNIT_TRAN;
			}
			set
			{
				if ((this._UNIT_TRAN != value))
				{
					this.OnUNIT_TRANChanging(value);
					this.SendPropertyChanging();
					this._UNIT_TRAN = value;
					this.SendPropertyChanged("UNIT_TRAN");
					this.OnUNIT_TRANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PRINTDATE
		{
			get
			{
				return this._PRINTDATE;
			}
			set
			{
				if ((this._PRINTDATE != value))
				{
					this.OnPRINTDATEChanging(value);
					this.SendPropertyChanging();
					this._PRINTDATE = value;
					this.SendPropertyChanged("PRINTDATE");
					this.OnPRINTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAUSE_REQUEST", DbType="VarChar(150)")]
		public string CAUSE_REQUEST
		{
			get
			{
				return this._CAUSE_REQUEST;
			}
			set
			{
				if ((this._CAUSE_REQUEST != value))
				{
					this.OnCAUSE_REQUESTChanging(value);
					this.SendPropertyChanging();
					this._CAUSE_REQUEST = value;
					this.SendPropertyChanged("CAUSE_REQUEST");
					this.OnCAUSE_REQUESTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GR_DOCNO", DbType="VarChar(50)")]
		public string GR_DOCNO
		{
			get
			{
				return this._GR_DOCNO;
			}
			set
			{
				if ((this._GR_DOCNO != value))
				{
					this.OnGR_DOCNOChanging(value);
					this.SendPropertyChanging();
					this._GR_DOCNO = value;
					this.SendPropertyChanged("GR_DOCNO");
					this.OnGR_DOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GR_YEAR", DbType="VarChar(10)")]
		public string GR_YEAR
		{
			get
			{
				return this._GR_YEAR;
			}
			set
			{
				if ((this._GR_YEAR != value))
				{
					this.OnGR_YEARChanging(value);
					this.SendPropertyChanging();
					this._GR_YEAR = value;
					this.SendPropertyChanged("GR_YEAR");
					this.OnGR_YEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTUSER", DbType="VarChar(50)")]
		public string PRINTUSER
		{
			get
			{
				return this._PRINTUSER;
			}
			set
			{
				if ((this._PRINTUSER != value))
				{
					this.OnPRINTUSERChanging(value);
					this.SendPropertyChanging();
					this._PRINTUSER = value;
					this.SendPropertyChanged("PRINTUSER");
					this.OnPRINTUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPROVEDATE
		{
			get
			{
				return this._APPROVEDATE;
			}
			set
			{
				if ((this._APPROVEDATE != value))
				{
					this.OnAPPROVEDATEChanging(value);
					this.SendPropertyChanging();
					this._APPROVEDATE = value;
					this.SendPropertyChanged("APPROVEDATE");
					this.OnAPPROVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVEUSER", DbType="VarChar(50)")]
		public string APPROVEUSER
		{
			get
			{
				return this._APPROVEUSER;
			}
			set
			{
				if ((this._APPROVEUSER != value))
				{
					this.OnAPPROVEUSERChanging(value);
					this.SendPropertyChanging();
					this._APPROVEUSER = value;
					this.SendPropertyChanged("APPROVEUSER");
					this.OnAPPROVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_REMARK", DbType="VarChar(200)")]
		public string APPROVE_REMARK
		{
			get
			{
				return this._APPROVE_REMARK;
			}
			set
			{
				if ((this._APPROVE_REMARK != value))
				{
					this.OnAPPROVE_REMARKChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_REMARK = value;
					this.SendPropertyChanged("APPROVE_REMARK");
					this.OnAPPROVE_REMARKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_PRE_Print_MessageSub")]
	public partial class TBTrans_PRE_Print_MessageSub : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private int _ROWORDER;
		
		private string _BRANCHCODE;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _MESSAGE;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private System.Nullable<System.DateTime> _PRINTDATE;
		
		private string _PRINTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnROWORDERChanging(int value);
    partial void OnROWORDERChanged();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnMESSAGEChanging(string value);
    partial void OnMESSAGEChanged();
    partial void OnQUANTITYChanging(System.Nullable<decimal> value);
    partial void OnQUANTITYChanged();
    partial void OnPRINTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPRINTDATEChanged();
    partial void OnPRINTUSERChanging(string value);
    partial void OnPRINTUSERChanged();
    #endregion
		
		public TBTrans_PRE_Print_MessageSub()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWORDER", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ROWORDER
		{
			get
			{
				return this._ROWORDER;
			}
			set
			{
				if ((this._ROWORDER != value))
				{
					this.OnROWORDERChanging(value);
					this.SendPropertyChanging();
					this._ROWORDER = value;
					this.SendPropertyChanged("ROWORDER");
					this.OnROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE", DbType="VarChar(200)")]
		public string MESSAGE
		{
			get
			{
				return this._MESSAGE;
			}
			set
			{
				if ((this._MESSAGE != value))
				{
					this.OnMESSAGEChanging(value);
					this.SendPropertyChanging();
					this._MESSAGE = value;
					this.SendPropertyChanged("MESSAGE");
					this.OnMESSAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Money")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PRINTDATE
		{
			get
			{
				return this._PRINTDATE;
			}
			set
			{
				if ((this._PRINTDATE != value))
				{
					this.OnPRINTDATEChanging(value);
					this.SendPropertyChanging();
					this._PRINTDATE = value;
					this.SendPropertyChanged("PRINTDATE");
					this.OnPRINTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTUSER", DbType="VarChar(50)")]
		public string PRINTUSER
		{
			get
			{
				return this._PRINTUSER;
			}
			set
			{
				if ((this._PRINTUSER != value))
				{
					this.OnPRINTUSERChanging(value);
					this.SendPropertyChanging();
					this._PRINTUSER = value;
					this.SendPropertyChanged("PRINTUSER");
					this.OnPRINTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_PRE_Print_Message")]
	public partial class TBTrans_PRE_Print_Message : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _BRANCHCODE;
		
		private System.DateTime _CREATEDATE;
		
		private string _CREATEUSER;
		
		private string _MAT_SELLER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnCREATEDATEChanging(System.DateTime value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATEUSERChanging(string value);
    partial void OnCREATEUSERChanged();
    partial void OnMAT_SELLERChanging(string value);
    partial void OnMAT_SELLERChanged();
    #endregion
		
		public TBTrans_PRE_Print_Message()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEUSER", DbType="VarChar(50)")]
		public string CREATEUSER
		{
			get
			{
				return this._CREATEUSER;
			}
			set
			{
				if ((this._CREATEUSER != value))
				{
					this.OnCREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._CREATEUSER = value;
					this.SendPropertyChanged("CREATEUSER");
					this.OnCREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_SELLER", DbType="VarChar(50)")]
		public string MAT_SELLER
		{
			get
			{
				return this._MAT_SELLER;
			}
			set
			{
				if ((this._MAT_SELLER != value))
				{
					this.OnMAT_SELLERChanging(value);
					this.SendPropertyChanging();
					this._MAT_SELLER = value;
					this.SendPropertyChanged("MAT_SELLER");
					this.OnMAT_SELLERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
